### ISSUE TITLE
Missing instruction-tuning data selection paper

### ISSUE THREAD

**Issue by dheeraj7596** [alon-albalak/data-selection-survey#1]
Great survey! Our paper on instruction-tuning data selection is missing here. We are one of the first papers to show that small models (350M) are capable of curating training data for large models (13B) which results in equally/more efficient than the large model trained on full training data. Hope you find this relevant.

Link: https://arxiv.org/pdf/2402.10430.pdf

**Comment by alon-albalak** [comment]
Thanks for contributing!

I added your paper in this commit: https://github.com/alon-albalak/data-selection-survey/commit/92915c9e6c09c477bc1274b163a28a9277f993bf

**Comment by alon-albalak** [comment]
Thanks for contributing!

I added your work in this commit: https://github.com/alon-albalak/data-selection-survey/commit/92915c9e6c09c477bc1274b163a28a9277f993bf
